### ISSUE TITLE
Support for Linux Snap

### ISSUE THREAD

**Issue by lawzava** [mallowigi/slack-themes#11]
I am having issues to install this on the snap version of slack (which happened to be more stable in general than from the source).

Changing the location to `/snap/slack/current/usr/lib/slack/resources` within lib/consts.js returned these logs:

```
(node:24742) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, copyfile '/snap/slack/current/usr/lib/slack/resources/app.asar' -> '/snap/slack/current/usr/lib/slack/resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1724:3)
    at Object.exports.apply (/home/z/tmp/slack-themes/lib/command.js:65:6)
    at Object.exports.selectTheme (/home/z/tmp/slack-themes/lib/command.js:97:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Tried with sudo as well, but I guess the directories are protected from write. 

What else could I try here? :thinking:

**Comment by mallowigi** [comment]
Yes I know, I have the same issue. So far I have no idea.
