### ISSUE TITLE
Can't install any theme

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [mallowigi/slack-themes#24]
OS: Windows 10

```
? Select a theme Material Palenight
Selected: palenight
current theme is now Material Palenight
Adding Material Palenight Theme Code to Slack...

(node:9864) UnhandledPromiseRejectionWarning: Error: EBUSY: resource busy or locked, open 'C:\Users\lilianaiturribarria\AppData\Local\slack\app-4.3.4\resources\app.asar.unpacked\node_modules\@nodert-win10-au\windows.data.xml.dom\build\Release\binding.node'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.module.exports.extractAll (C:\Users\lilianaiturribarria\AppData\Roaming\npm\node_modules\@mallowigi\slack-themes\node_modules\asar\lib\asar.js:201:10)
    at Object.exports.apply (C:\Users\lilianaiturribarria\AppData\Roaming\npm\node_modules\@mallowigi\slack-themes\lib\command.js:75:8)
    at Object.exports.selectTheme (C:\Users\lilianaiturribarria\AppData\Roaming\npm\node_modules\@mallowigi\slack-themes\lib\command.js:105:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mallowigi** [comment]
Sorry, can't make it work for Windows as I don't have a Windows environment.
