### ISSUE TITLE
UnhandledPromiseRejectionWarning Error on Windows 10

### ISSUE THREAD

**Issue by CharlieEtienne** [mallowigi/slack-themes#42]
Hi, 

I can't make it work on Windows 10, I get this error message when I try to select Apply and hit enter:

```
? Please select an command Apply theme
Removing theme...

Successfully removed!

current theme is now Material Oceanic
Adding Theme Code to Slack...

(node:31252) UnhandledPromiseRejectionWarning: Error: EBUSY: resource busy or locked, open 'C:\Users\Charlie\AppData\Local\slack\app-4.6.0\resources\app.asar.unpacked\node_modules\@marshallofsound\native-keymap\build\Release\keymapping.node'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.module.exports.extractAll (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\node_modules\@mallowigi\asar\lib\asar.js:201:10)
    at Object.exports.apply (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:91:8)
    at Object.exports.selectTheme (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:126:8)
    at Object.exports.change (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:117:8)
    at exports.execute.answer (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:132:12)
    at run (C:\Users\Charlie\AppData\Roaming\npm\node_modules\mtslack\main.js:27:3)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:31252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by CharlieEtienne** [comment]
Actually it works after closing slack and killing all Slack processes in Task Manager
